export function getDomElements() {
  return {
    cardsEl: document.getElementById("cards"),
    emailsBodyEl: document.getElementById("emails-body"),
    tableTitleEl: document.getElementById("table-title"),
    healthIndicatorEl: document.getElementById("health-indicator"),
    dateFilterInputEl: document.getElementById("date-filter-input"),
    refreshBtnEl: document.getElementById("refresh-btn"),
    clearFilterBtnEl: document.getElementById("clear-filter-btn"),
    modalEl: document.getElementById("email-modal"),
    modalCloseBtnEl: document.getElementById("modal-close-btn"),
    modalStatusSelectEl: document.getElementById("modal-status-select"),
    saveStatusBtnEl: document.getElementById("save-status-btn"),
    modalSubjectEl: document.getElementById("modal-subject"),
    modalSummaryEl: document.getElementById("modal-summary"),
    modalOverviewEl: document.getElementById("modal-overview"),
    modalBodyEl: document.getElementById("modal-body"),
    modalClassificationEl: document.getElementById("modal-classification"),
    modalExtractionEl: document.getElementById("modal-extraction"),
    modalInvoiceEl: document.getElementById("modal-invoice"),
    modalReplyEl: document.getElementById("modal-reply"),
    sendReplyBtnEl: document.getElementById("send-reply-btn"),
    tabOverviewEl: document.getElementById("tab-overview"),
    tabEvidenceEl: document.getElementById("tab-evidence"),
    tabReplyEl: document.getElementById("tab-reply"),
    panelOverviewEl: document.getElementById("panel-overview"),
    panelEvidenceEl: document.getElementById("panel-evidence"),
    panelReplyEl: document.getElementById("panel-reply"),
  };
}
